// Auto-generated by stellar-contracts-kit
// Contract : CCOSIY3DGKKTOVJKTCIK4PVY4XZ75GMOBI256WDQRDEPIANPGOMXDC3J
// Network  : mainnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Custom Types

/** @typedef {{ hash: Uint8Array, id: number, owner: string, timestamp: bigint }} ExpenseProof */

// Contract Interface

/**
 * @typedef {Object} proofspend
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<string>, []>} hello
 * @property {import('stellar-contracts-kit').ContractMethodFn<number, [owner: string, hash: Uint8Array]>} add_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<ExpenseProof | null, [id: number]>} get_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<boolean, [id: number, hash: Uint8Array]>} verify_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<number>, [owner: string]>} get_user_expenses
 */

export const CONTRACT_ID = 'CCOSIY3DGKKTOVJKTCIK4PVY4XZ75GMOBI256WDQRDEPIANPGOMXDC3J'
