// Auto-generated by stellar-contracts-kit
// Example usage for proofspend
// Contract : CCOSIY3DGKKTOVJKTCIK4PVY4XZ75GMOBI256WDQRDEPIANPGOMXDC3J
// Network  : mainnet
// @ts-check

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/proofspend.js. Update the path below if using snippets elsewhere.
import { CONTRACT_ID } from './proofspend.js'

const kit = new StellarContractsKit({ network: 'mainnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the contract client
const contract = await kit.contract(CONTRACT_ID)

// hello() -> Array<string>
const { result: helloResult } = await contract.hello.read()
console.log('hello:', helloResult)

// add_expense(owner: string, hash: Uint8Array) -> number
const { txHash: add_expenseTxHash, result: add_expenseResult } = await contract.add_expense.invoke(
  'G...',  // owner: string
  new Uint8Array(),  // hash: Uint8Array
)
console.log('add_expense txHash:', add_expenseTxHash, 'result:', add_expenseResult)

// get_expense(id: number) -> ExpenseProof | null
const { txHash: get_expenseTxHash, result: get_expenseResult } = await contract.get_expense.invoke(
  0,  // id: number
)
console.log('get_expense txHash:', get_expenseTxHash, 'result:', get_expenseResult)

// verify_expense(id: number, hash: Uint8Array) -> boolean
const { txHash: verify_expenseTxHash, result: verify_expenseResult } = await contract.verify_expense.invoke(
  0,  // id: number
  new Uint8Array(),  // hash: Uint8Array
)
console.log('verify_expense txHash:', verify_expenseTxHash, 'result:', verify_expenseResult)

// get_user_expenses(owner: string) -> Array<number>
const { txHash: get_user_expensesTxHash, result: get_user_expensesResult } = await contract.get_user_expenses.invoke(
  'G...',  // owner: string
)
console.log('get_user_expenses txHash:', get_user_expensesTxHash, 'result:', get_user_expensesResult)
