// Auto-generated by stellar-contracts-kit
// Contract : CA6ICDSUSPUT3WP4BX3CE3QKLJHVG5SE2LH5B6I77743WAO5GQ5BN55Y
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Custom Types

/** @typedef {{ hash: Uint8Array, id: number, owner: string, timestamp: bigint }} ExpenseProof */

// Contract Interface

/**
 * @typedef {Object} proofspend
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<string>, []>} hello
 * @property {import('stellar-contracts-kit').ContractMethodFn<number, [owner: string, hash: Uint8Array]>} add_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<ExpenseProof | null, [id: number]>} get_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<boolean, [id: number, hash: Uint8Array]>} verify_expense
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<number>, [owner: string]>} get_user_expenses
 */

export const CONTRACT_ID = 'CA6ICDSUSPUT3WP4BX3CE3QKLJHVG5SE2LH5B6I77743WAO5GQ5BN55Y'
